export const PopularItems = [
  {
    id: 1,
    title: "Fried Rice",
    Price: 80,
    Description: "eMVee Restaurant",
    Ingredients: "Fermented local ingredients",
    image: require("../../assets/Friedrice.jpg"),
  },
  {
    id: 2,
    title: "Grilled Chicken",
    Price: 190,
    Description: "eMVee Restaurant",
    image: require("../../assets/chickengrill.jpg"),
  },
  {
    id: 3,
    title: "Octopus Stir Fried",
    Price: 400,
    Description: "eMVee Restaurant",
    image: require("../../assets/octstir.jpg"),
  },
  {
    id: 4,
    title: "Porkribs",
    Price: 270,
    Description: "eMVee Restaurant",
    image: require("../../assets/Porkribs.jpg"),
  },
  {
    id: 5,
    title: "Prawn Fried",
    Price: 290,
    Description: "eMVee Restaurant",
    image: require("../../assets/Prawnfried.jpg"),
  },
  {
    id: 6,
    title: "Thukpa",
    Price: 80,
    Description: "eMVee Restaurant",
    image: require("../../assets/Thukpa.jpg"),
  },
];

export const AllProductsData = [
  {
    id: 1,
    title: "Fried Rice",
    Price: 80,
    Description: "eMVee Restaurant",
    Ingredients: "Fermented local ingredients",
    image: require("../../assets/Friedrice.jpg"),
    p: true,
  },
  {
    id: 2,
    title: "Grilled Chicken",
    Price: 190,
    Description: "eMVee Restaurant",
    image: require("../../assets/chickengrill.jpg"),
    p: true,
  },
  {
    id: 3,
    title: "Octopus Stir Fried",
    Price: 400,
    Description: "eMVee Restaurant",
    image: require("../../assets/octstir.jpg"),
    p: true,
  },
  {
    id: 4,
    title: "Porkribs",
    Price: 270,
    Description: "eMVee Restaurant",
    image: require("../../assets/Porkribs.jpg"),
    p: true,
  },
  {
    id: 5,
    title: "Prawn Fried",
    Price: 290,
    Description: "eMVee Restaurant",
    image: require("../../assets/Prawnfried.jpg"),
    p: true,
  },
  {
    id: 6,
    title: "Thukpa",
    Price: 80,
    Description: "eMVee Restaurant",
    image: require("../../assets/Thukpa.jpg"),
    p: true,
  },
];

export const TotalCategoryList = [
  {
    id: 1,
    title: "Signature Dishes",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 2,
    title: "emVEee Special",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 3,
    title: "Rolls",
    image: require("../../assets/images/category/rolls.webp"),
    p: true,
  },
  {
    id: 4,
    title: "Sea Food",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 5,
    title: "Salad",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 6,
    title: "Paratha Combo",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 7,
    title: "Burger",
    image: require("../../assets/images/category/burger.png"),
    p: true,
  },
  {
    id: 8,
    title: "Beverages",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 9,
    title: "Pizza",
    image: require("../../assets/images/category/pizza.png"),
    p: true,
  },
  {
    id: 10,
    title: "Appetizers",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 12,
    title: "Noodles",
    image: require("../../assets/images/category/noodles.webp"),
    p: true,
  },
  {
    id: 13,
    title: "Macs & Cheeses",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 14,
    title: "Soups",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 15,
    title: "Main Course",
    image: require("../../assets/images/category/drinks.webp"),
  },
  {
    id: 16,
    title: "Momos",
    image: require("../../assets/images/category/momos.webp"),
    p: true,
  },
  {
    id: 17,
    title: "Fried Rice",
    image: require("../../assets/images/category/drinks.webp"),
    p: true,
  },
  {
    id: 18,
    title: "Thukpa",
    image: require("../../assets/images/category/drinks.webp"),
  },
];
