// ALL CATEGORIES
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const RESET_CATEGORIES = "RESET_CATEGORIES";

// SINGLE CATEGORY
export const ADD_SINGLE_CATEGORY = "ADD_SINGLE_CATEGORY";
export const EDIT_SINGLE_CATEGORY = "EDIT_SINGLE_CATEGORY";
export const REMOVE_SINGLE_CATEGORY = "REMOVE_SINGLE_CATEGORY";
