// ALL PRODUCTS
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const RESET_PRODUCTS = "RESET_PRODUCTS";

// SINGLE PRODUCT
export const ADD_SINGLE_PRODUCT = "ADD_SINGLE_PRODUCT";
export const EDIT_SINGLE_PRODUCT = "EDIT_SINGLE_PRODUCT";
export const REMOVE_SINGLE_PRODUCT = "REMOVE_SINGLE_PRODUCT";
