// ALL ORDERS
export const RESET_ORDERS = "RESET_ORDERS";

// SINGLE ORDER
export const ADD_ORDER = "ADD_ORDER";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const DELIVER_ORDER_REDUCER = "DELIVER_ORDER_REDUCER";
